crud/urls.py
from django.urls import path

from . import views

app_name = "crud"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("edit/<int:client_id>", views.edit, name="edit"),
    path("delete/<int:client_id>", views.delete, name="delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crud.urls")),
]

crud/models.py
from django.db import models


class Client(models.Model):
    full_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=192)

    def __str__(self):
        return self.full_name

crud/forms.py
from django import forms
from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ["full_name", "email"]

crud/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from .forms import ClientForm
from .models import Client


def dashboard(request):
    if request.method == "POST":
        form = ClientForm(request.POST or None)
        if form.is_valid():
            form.save()
            clients = Client.objects.all()
            messages.success(request, "Client has been added!")
            return render(request, "crud/dashboard.html", {"clients": clients})
    else:
        clients = Client.objects.all()
        return render(request, "crud/dashboard.html", {"clients": clients})


def edit(request, client_id):
    if request.method == "POST":
        client = Client.objects.get(id=client_id)
        form = ClientForm(request.POST or None, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, "Client has been edited!")
            return redirect("/")
    else:
        client = Client.objects.get(id=client_id)
        clients = Client.objects.all()
        return render(
            request,
            "crud/dashboard.html",
            {"client": client, "clients": clients},
        )


def delete(request, client_id):
    client = Client.objects.get(id=client_id)
    client.delete()
    messages.success(request, "Client has been Deleted!")
    return redirect("/")

crud/templates/crud/blocks/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/all.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bulma.min.css' %}">

<script type="text/javascript" src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dataTables.bulma.min.js' %}"></script>

crud/templates/crud/blocks/header.html
<header class="main-header-container">
    <section class="hero is-small is-primary">
        <div class="hero-body">
            <h1 class="title is-1">
                <a href="{% url 'crud:dashboard' %}">Clients</a>
            </h1>
        </div>
    </section>
</header>

crud/templates/crud/blocks/list.html
<div class="column is-7">
    <h2 class="title is-2">List Customers</h2>
    <div class="container">
        <table id="example" class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th align="center">Edit</th>
                    <th align="center">Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <td>
                        <span>{{ client.full_name }}</span>
                    </td>
                    <td>
                        <span>{{ client.email }}</span>
                    </td>
                    <td align="center">
                        <a href="{% url 'crud:edit' client.id %}">
                            <span class="icon is-small">
                                <i class="fas fa-file-pen"></i>
                            </span>
                        </a>
                    </td>
                    <td align="center">
                        <a href="{% url 'crud:delete' client.id %}">
                            <span class="icon is-small">
                                <i class="fas fa-trash-can"></i>
                            </span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th align="center">Edit</th>
                    <th align="center">Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

crud/templates/crud/blocks/messages.html
<div class="columns">
    <div class="column">
        <h2 class="title is-2">Messages</h2>
    </div>
</div>

<div class="columns">
    <div class="column">
        {% if messages %}
            {% for message in messages %}
                <article class="message is-success">
                    <div class="message-header">
                        <p>Nice!</p>
                    </div>
                    <div class="message-body">
                        {{ message }}
                    </div>
                </article>
            {% endfor %}
        {% endif %}
    </div>
</div>

crud/templates/crud/blocks/register.html
<div class="column is-4">
    {% if client %}
        <h2 class="title is-2">Update Client</h2>
    {% else %}
        <h2 class="title is-2">Register Client</h2>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {% if client %}
            <div class="field">
                <label class="label">ID</label>
                <div class="control has-icons-left">
                    <input name="id" class="input is-success" type="text" value="{{ client.id }}" disabled>
                    <span class="icon is-small is-left">
                        <i class="fas fa-fingerprint"></i>
                    </span>
                </div>
            </div>
        {% endif %}
        <div class="field">
            <label class="label">Full Name</label>
            <div class="control has-icons-left">
                <input name="full_name" class="input is-success" type="text" placeholder="Text input" value="{{ client.full_name }}" required>
                <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                </span>
            </div>
        </div>
        <div class="field">
            <label class="label">Email</label>
            <div class="control has-icons-left has-icons-right">
                <input name="email" class="input is-success" type="email" placeholder="Email input" value="{{ client.email }}" required>
                <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                </span>
            </div>
        </div>
        <div class="field is-grouped">
            <div class="control">
                {% if client %}
                    <button type="submit" class="button is-link">Update</button>
                {% else %}
                    <button type="submit" class="button is-link">Register</button>
                {% endif %}
            </div>
            <div class="control">
                <button type="reset" class="button is-link is-light" onclick="location.href = '{% url 'crud:dashboard' %}'">Cancel</button>
            </div>
        </div>
    </form>
</div>

<div class="column is-1">

</div>

crud/templates/crud/dashboard.html
<!doctype html>
<html lang="pt-BR">
<head>
    {% include 'crud/blocks/head.html' %}
    <title>Dashboard Clients</title>
</head>
<body>

{% include 'crud/blocks/header.html' %}

<div class="container is-max-widescreen" style="margin-top: 25px">
    <div class="columns">

        {% include 'crud/blocks/register.html' %}

        {% include 'crud/blocks/list.html' %}

    </div>

    {% include 'crud/blocks/messages.html' %}
</div>

<script>
    $(document).ready(function () {
        $('#example').DataTable({
            columns: [
                null,
                null,
                {orderable: false, searchable: false},
                {orderable: false, searchable: false},
            ],
            lengthMenu: [
                [5, 10, 15, -1],
                [5, 10, 15, 'All'],
            ],
        });
    });
</script>

</body>
</html>